name: petridishpytorch
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - autopep8=1.4.4=py_0
  - backcall=0.1.0=py36_0
  - blas=1.0=mkl
  - ca-certificates=2019.10.16=0
  - certifi=2019.9.11=py36_0
  - cffi=1.12.1=py36h2e261b9_0
  - cudatoolkit=10.1.168=0
  - decorator=4.3.2=py36_0
  - freetype=2.9.1=h8a8886c_1
  - importlib_metadata=0.23=py36_0
  - intel-openmp=2019.1=144
  - ipython=7.8.0=py36h39e3cac_0
  - ipython_genutils=0.2.0=py36_0
  - jedi=0.13.3=py36_0
  - jpeg=9b=h024ee3a_2
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.36=hbc83047_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.10=h2733197_2
  - mkl=2019.1=144
  - mkl_fft=1.0.10=py36ha843d7b_0
  - mkl_random=1.0.2=py36hd81dba3_0
  - more-itertools=7.2.0=py36_0
  - ncurses=6.1=he6710b0_1
  - ninja=1.8.2=py36h6bb024c_1
  - numpy=1.15.4=py36h7e9f1db_0
  - numpy-base=1.15.4=py36hde5b4d6_0
  - olefile=0.46=py36_0
  - openssl=1.1.1d=h7b6447c_3
  - packaging=19.2=py_0
  - parso=0.3.4=py36_0
  - pexpect=4.6.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pillow=5.4.1=py36h34e0f95_0
  - pip=19.0.3=py36_0
  - prompt_toolkit=2.0.9=py36_0
  - ptyprocess=0.6.0=py36_0
  - py=1.8.0=py36_0
  - pycodestyle=2.5.0=py36_0
  - pycparser=2.19=py36_0
  - pygments=2.3.1=py36_0
  - python=3.6.8=h0371630_0
  - pytorch=1.3.0=py3.6_cuda10.1.243_cudnn7.6.3_0
  - readline=7.0=h7b6447c_5
  - six=1.12.0=py36_0
  - sqlite=3.26.0=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - torchvision=0.4.1=py36_cu101
  - traitlets=4.3.2=py36_0
  - wcwidth=0.1.7=py36_0
  - wheel=0.33.1=py36_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - absl-py==0.8.1
    - adal==1.2.2
    - applicationinsights==0.11.9
    - atomicwrites==1.3.0
    - attrs==19.2.0
    - azure==4.0.0
    - azure-applicationinsights==0.1.0
    - azure-batch==4.1.3
    - azure-common==1.1.23
    - azure-cosmosdb-nspkg==2.0.2
    - azure-cosmosdb-table==1.0.6
    - azure-datalake-store==0.0.48
    - azure-eventgrid==1.3.0
    - azure-graphrbac==0.40.0
    - azure-keyvault==1.1.0
    - azure-loganalytics==0.1.0
    - azure-mgmt==4.0.0
    - azure-mgmt-advisor==1.0.1
    - azure-mgmt-applicationinsights==0.1.1
    - azure-mgmt-authorization==0.50.0
    - azure-mgmt-batch==5.0.1
    - azure-mgmt-batchai==2.0.0
    - azure-mgmt-billing==0.2.0
    - azure-mgmt-cdn==3.1.0
    - azure-mgmt-cognitiveservices==3.0.0
    - azure-mgmt-commerce==1.0.1
    - azure-mgmt-compute==4.6.2
    - azure-mgmt-consumption==2.0.0
    - azure-mgmt-containerinstance==1.5.0
    - azure-mgmt-containerregistry==2.8.0
    - azure-mgmt-containerservice==4.4.0
    - azure-mgmt-cosmosdb==0.4.1
    - azure-mgmt-datafactory==0.6.0
    - azure-mgmt-datalake-analytics==0.6.0
    - azure-mgmt-datalake-nspkg==3.0.1
    - azure-mgmt-datalake-store==0.5.0
    - azure-mgmt-datamigration==1.0.0
    - azure-mgmt-devspaces==0.1.0
    - azure-mgmt-devtestlabs==2.2.0
    - azure-mgmt-dns==2.1.0
    - azure-mgmt-eventgrid==1.0.0
    - azure-mgmt-eventhub==2.6.0
    - azure-mgmt-hanaonazure==0.1.1
    - azure-mgmt-iotcentral==0.1.0
    - azure-mgmt-iothub==0.5.0
    - azure-mgmt-iothubprovisioningservices==0.2.0
    - azure-mgmt-keyvault==1.1.0
    - azure-mgmt-loganalytics==0.2.0
    - azure-mgmt-logic==3.0.0
    - azure-mgmt-machinelearningcompute==0.4.1
    - azure-mgmt-managementgroups==0.1.0
    - azure-mgmt-managementpartner==0.1.1
    - azure-mgmt-maps==0.1.0
    - azure-mgmt-marketplaceordering==0.1.0
    - azure-mgmt-media==1.0.0
    - azure-mgmt-monitor==0.5.2
    - azure-mgmt-msi==0.2.0
    - azure-mgmt-network==2.7.0
    - azure-mgmt-notificationhubs==2.1.0
    - azure-mgmt-nspkg==3.0.2
    - azure-mgmt-policyinsights==0.1.0
    - azure-mgmt-powerbiembedded==2.0.0
    - azure-mgmt-rdbms==1.9.0
    - azure-mgmt-recoveryservices==0.3.0
    - azure-mgmt-recoveryservicesbackup==0.3.0
    - azure-mgmt-redis==5.0.0
    - azure-mgmt-relay==0.1.0
    - azure-mgmt-reservations==0.2.1
    - azure-mgmt-resource==2.2.0
    - azure-mgmt-scheduler==2.0.0
    - azure-mgmt-search==2.1.0
    - azure-mgmt-servicebus==0.5.3
    - azure-mgmt-servicefabric==0.2.0
    - azure-mgmt-signalr==0.1.1
    - azure-mgmt-sql==0.9.1
    - azure-mgmt-storage==2.0.0
    - azure-mgmt-subscription==0.2.0
    - azure-mgmt-trafficmanager==0.50.0
    - azure-mgmt-web==0.35.0
    - azure-nspkg==3.0.2
    - azure-servicebus==0.21.1
    - azure-servicefabric==6.3.0.0
    - azure-servicemanagement-legacy==0.20.6
    - azure-storage-blob==1.5.0
    - azure-storage-common==1.4.2
    - azure-storage-file==1.4.0
    - azure-storage-queue==1.4.0
    - azureml-core==1.0.74
    - azureml-dataprep==1.1.31
    - azureml-dataprep-native==13.1.0
    - azureml-pipeline==1.0.74
    - azureml-pipeline-core==1.0.74
    - azureml-pipeline-steps==1.0.74
    - azureml-sdk==1.0.74
    - azureml-telemetry==1.0.74
    - azureml-train==1.0.74
    - azureml-train-core==1.0.74
    - azureml-train-restclients-hyperdrive==1.0.74
    - backports-tempfile==1.0
    - backports-weakref==1.0.post1
    - bleach==3.1.0
    - cachetools==3.1.1
    - chardet==3.0.4
    - click==7.0
    - cloudpickle==1.2.2
    - colorama==0.4.1
    - contextlib2==0.6.0.post1
    - cryptography==2.8
    - cycler==0.10.0
    - defusedxml==0.6.0
    - distro==1.4.0
    - docker==4.1.0
    - docs==0.2.2
    - dotnetcore2==2.1.11
    - entrypoints==0.3
    - enum34==1.1.6
    - filelock==3.0.12
    - funcsigs==1.0.2
    - fusepy==3.0.1
    - future==0.18.2
    - gitdb2==2.0.6
    - gitpython==3.0.3
    - google-auth==1.7.0
    - google-auth-oauthlib==0.4.1
    - gorilla==0.3.0
    - grpcio==1.25.0
    - hyperopt==0.1.2
    - idna==2.8
    - imageio==2.6.1
    - ipykernel==5.1.3
    - ipywidgets==7.5.1
    - isodate==0.6.0
    - jeepney==0.4.1
    - jinja2==2.10.3
    - jmespath==0.9.4
    - joblib==0.14.0
    - jsonpickle==1.2
    - jsonschema==3.0.2
    - jupyter-client==5.3.4
    - jupyter-core==4.6.1
    - kiwisolver==1.1.0
    - markdown==3.1.1
    - markupsafe==1.1.1
    - matplotlib==3.1.1
    - mistune==0.8.4
    - msrest==0.6.10
    - msrestazure==0.6.2
    - munch==2.3.2
    - nbconvert==5.6.1
    - nbformat==4.4.0
    - ndg-httpsclient==0.5.1
    - networkx==2.2
    - notebook==6.0.2
    - oauthlib==3.1.0
    - overrides==2.6
    - pandas==0.25.3
    - pandocfilters==1.4.2
    - pathspec==0.6.0
    - plotly==4.3.0
    - pluggy==0.13.0
    - pretrainedmodels==0.7.4
    - prometheus-client==0.7.1
    - protobuf==3.10.0
    - psutil==5.6.3
    - pyasn1==0.4.7
    - pyasn1-modules==0.2.7
    - pydot==1.4.1
    - pyjwt==1.7.1
    - pymongo==3.9.0
    - pyopenssl==19.0.0
    - pyparsing==2.4.2
    - pyrsistent==0.15.4
    - pystopwatch2==0.1.1
    - pytest==5.2.1
    - python-dateutil==2.8.0
    - python-graphviz==0.13.2
    - pytz==2019.3
    - pywavelets==1.1.1
    - pyyaml==5.1.2
    - pyzmq==18.1.0
    - ray==0.7.5
    - redis==3.3.8
    - requests==2.22.0
    - requests-oauthlib==1.3.0
    - retrying==1.3.3
    - rsa==4.0
    - ruamel-yaml==0.15.89
    - scikit-image==0.16.2
    - scikit-learn==0.21.3
    - scipy==1.3.1
    - secretstorage==3.1.1
    - send2trash==1.5.0
    - setuptools==41.6.0
    - sklearn==0.0
    - smmap2==2.0.5
    - tensorboard==2.0.1
    - tensorboardx==1.9
    - terminado==0.8.3
    - testpath==0.4.4
    - theconf==0.1.0
    - timebudget==0.7
    - torchstat==0.0.7
    - tornado==6.0.3
    - tqdm==4.36.1
    - urllib3==1.25.6
    - warmup-scheduler==0.1
    - webencodings==0.5.1
    - websocket-client==0.56.0
    - werkzeug==0.16.0
    - widgetsnbextension==3.5.1
prefix: /home/dedey/miniconda3/envs/petridishpytorch

